name: geepers-env
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - pip>=21.3  # https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/#editable-installation
  - git  # for pip install, due to setuptools_scm
  - pandas
  - lxml
  - geopandas-base
  - pyogrio
  - xarray
  - dask>=2025
  - pyproj
  - rasterio
  - rioxarray
  - scipy
  - shapely>=2
  - requests
  - tqdm
  - zarr
  - tyro>=0.9.24
  - pandera
