# SPDX-FileCopyrightText: 2025-2026 California Institute of Technology ("Caltech")
# SPDX-License-Identifier: Apache-2.0
# Part of geepers, https://github.com/opera-adt/geepers. If you copy or adapt
# any of this code, keep this notice and cite the repository (see NOTICE).
"""Copyright (c) 2023 Scott Staniewicz. All rights reserved.

geepers: Download GPS data and compare to InSAR
"""

from __future__ import annotations

# _version.py is autogenerated by setuptools_scm
from geepers._version import version as __version__

from .gps import *
from .io import *
from .schemas import *
from .uncertainty import *

__all__ = ["__version__"]
